---
- name: Deploy Nginx container
  hosts: ansible-server
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy application files
      copy:
        src: ./index.html
        dest: /opt/index.html

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /opt/Dockerfile

    - name: Build Docker image
      command: docker build -t my-nginx /opt

    - name: Run Docker container
      command: docker run -d -p 80:80 --name nginx-container my-nginx
