- name: Deploy Python App in Docker
  hosts: ec2
  become: yes
  tasks:
    - name: Pull Docker image
      command: docker pull your-dockerhub-username/python-flask-app:latest

    - name: Remove old container if exists
      command: docker rm -f flaskapp
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name flaskapp -p 80:80 your-dockerhub-username/python-flask-app:latest

